Repository agenda/agenda, pull requests merged in 2018-07, with the labels that each got.

#616 Update native mongodb driver to v3 from v2
  lib/agenda/database.js
  package.json
  test/agenda.js
  test/job.js
  test/retry.js
  yarn.lock
Labels: enhancement

#656 Feature/update deps
  lib/agenda/database.js
  lib/agenda/every.js
  lib/agenda/find-and-lock-next-job.js
  lib/agenda/index.js
  lib/agenda/locklimit.js
  lib/agenda/now.js
  lib/agenda/purge.js
  lib/agenda/save-job.js
  lib/agenda/schedule.js
  lib/agenda/start.js
  lib/job/compute-next-run-at.js
  lib/job/index.js
  lib/job/run.js
  lib/job/save.js
  lib/no-callback.js
  lib/utils/process-jobs.js
  package.json
  test/agenda.js
  test/job.js
  test/retry.js
  yarn.lock
Labels: deps:update

#657 Add a feature comparison table to readme
  README.md
Labels: docs

#660 add deps:update to renovate auto labels
  renovate.json
Labels: build tools

#667 Make job.touch() promise-based
  README.md
  lib/job/touch.js
  test/job.js
Labels: bug
