Repository agenda/agenda, pull requests merged in 2018-06, with the labels that each got.

#596 Document `skipImmediate` option
  README.md
Labels: docs

#608 Drop Node.js 4,5 and 6 testing from Travis
  .travis.yml
  History.md
  README.md
Labels: build tools, docs

#609 Update History.md for the next version
  History.md
Labels: docs

#603 Add an FAQ answer about the difference between `lockLimit` and `maxConcurrency`
  README.md
Labels: docs

#605 Update README.md to have correct priority mapping
  README.md
Labels: docs

#557 Promise rewrite
  .gitignore
  .jsdoc.json
  README.md
  lib/agenda/cancel.js
  lib/agenda/create.js
  lib/agenda/database.js
  lib/agenda/db-init.js
  lib/agenda/default-concurrency.js
  lib/agenda/default-lock-lifetime.js
  lib/agenda/default-lock-limit.js
  lib/agenda/define.js
  lib/agenda/every.js
  lib/agenda/find-and-lock-next-job.js
  lib/agenda/index.js
  lib/agenda/jobs.js
  lib/agenda/locklimit.js
  lib/agenda/max-concurrency.js
  lib/agenda/mongo.js
  lib/agenda/name.js
  lib/agenda/now.js
  lib/agenda/process-every.js
  lib/agenda/purge.js
  lib/agenda/save-job.js
  lib/agenda/schedule.js
  lib/agenda/sort.js
  lib/agenda/start.js
  lib/agenda/stop.js
  lib/job/compute-next-run-at.js
  lib/job/disable.js
  lib/job/enable.js
  lib/job/fail.js
  lib/job/index.js
  lib/job/is-running.js
  lib/job/priority.js
  lib/job/remove.js
  lib/job/repeat-at.js
  lib/job/repeat-every.js
  lib/job/run.js
  lib/job/save.js
  lib/job/schedule.js
  lib/job/to-json.js
  lib/job/touch.js
  lib/job/unique.js
  lib/no-callback.js
  lib/utils/create-job.js
  lib/utils/process-jobs.js
  package.json
  test/agenda.js
  test/fixtures/agenda-instance.js
  test/job.js
  test/retry.js
  yarn.lock
Labels: enhancement, need: add to docs, planned

#611 Add Azure cosmosDB issue to FAQ
  README.md
Labels: docs

#615 Tests: test `lastRunAt` not `nextRunAt` for FIFO tests
  test/job.js
Labels: bug

#614 Fix typos and mistakes in docs
  README.md
  lib/agenda/schedule.js
Labels: docs

#624 Remove comments refrencing deprecated findAndModify
  lib/agenda/index.js
  lib/agenda/save-job.js
Labels: docs
