Repository agenda/agenda, pull requests merged in 2020-02, with the labels that each got.

#925 Drop Node.js 8 support
  .travis.yml
  History.md
  package.json
Labels: build tools

#921 Support of MongoDB: Unified Topology Design
  lib/agenda/find-and-lock-next-job.js
  lib/agenda/index.js
  lib/utils/process-jobs.js
  test/connection-use-unified-topology.js
Labels: enhancement

#860 Fix for skipImmediate resetting nextRunAt to current date
  lib/job/repeat-every.js
  test/job.js
Labels: bug
