Repository agenda/agenda, pull requests merged in 2021-01, with the labels that each got.

#450 [WIP] Add close method
  README.md
  lib/agenda/close.ts
  lib/agenda/index.ts
  test/agenda.js
Labels: enhancement, need: +1, need: tests

#1193 Use dist instead of lib and compile TS before publish
  index.js
  package.json
Labels: bug

#794 Example illustrating concurrency and locking
  examples/concurrency.js
Labels: need: +1
